services:
  spark:
    build: .
    container_name: tradecorp_spark
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/work
      - ./src:/home/jovyan/src
      - ./tests:/home/jovyan/tests
      
    env_file:
      - .env  
    environment:
      PYSPARK_SUBMIT_ARGS: "--packages org.postgresql:postgresql:42.7.0 pyspark-shell"

# ajout du service postgres
  postgres:
    image: postgres:16
    container_name: tradecorp_postgres
    environment:
      POSTGRES_USER: tradecorp
      POSTGRES_PASSWORD: tradecorp
      POSTGRES_DB: tradecorp
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: tradecorp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres


  # Service Apache Airflow
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: tradecorp_airflow
    depends_on: 
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://tradecorp:tradecorp@postgres/tradecorp
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports: ["8080:8080"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
      - /var/run/docker.sock:/var/run/docker.sock
    # On utilise les variables d'environnement (avec repli sur des valeurs par défaut)
    command: bash -c "sleep 10 && airflow db init && airflow db migrate && airflow users create --username $${AIRFLOW_ADMIN_USER:-admin} --password $${AIRFLOW_ADMIN_PASSWORD:-admin} --firstname Admin --lastname Admin --role Admin --email $${AIRFLOW_ADMIN_EMAIL:-admin@admin.com} && airflow scheduler & exec airflow webserver"

# Service Apache Airflow (Scheduler séparé)
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: tradecorp_airflow_scheduler
    depends_on: 
      - airflow
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://tradecorp:tradecorp@postgres/tradecorp
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      # Pour autoriser l'affichage des logs sans blocage 403 :
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
      - /var/run/docker.sock:/var/run/docker.sock
    command: airflow scheduler
    
volumes:
  pgdata: