services:
  spark:
    image: quay.io/jupyter/pyspark-notebook
    container_name: tradecorp_spark
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/work
